resolver: lts-7.20 # 8.5
compiler: ghc-8.0.1

nix:
  enable: true
  pure: true
  packages:
  - zlib
  # shell-file: shell.nix

packages:
- ./
- ../speech/spiros

extra-deps: 
- spiros-0.0.0

# -I nixpkgs=~/nixpkgs
